stages:
- build
- release

build:
  image: node:16
  stage: build
  script:
  - dpkg --add-architecture i386
  - apt-get update -qy
  - apt-get -y install curl wine32
  - npm i
  - npm run updatePreview
  - npm run build-all
  artifacts:
    expire_in: 1 yr
    paths:
    - dist_electron/*.zip
    - dist_electron/*.deb
    - dist_electron/*.exe
  only:
  - main
  - web
  - tags

release:
  stage: release
  needs: 
    - build
  script:
    - ls
  only:
  - tags
