stages:
  - build
build:
  image: node:16
  stage: build
  script:
    - npm i
    - npm run updatePreview
    - npm run build -- -- --publish never
  artifacts:
    expire_in: 1 week
    paths:
      - dist_electron/*

