stages:
  - build
  - buildAll
  - sign

build:
  image: node:18
  stage: build
  script:
    - npm i
    - npm run updatePreview
    - npm run build -- -- --publish never
  artifacts:
    expire_in: 1 week
    paths:
      - dist_electron/*
  only:
    - main
  tags:
    - gitlab-ci-learninglab-4

buildAll:
  image: node:18
  stage: build
  script:
    - npm i
    - npm i --save-optional dmg-license
    - npm run updatePreview
    - npm run build -- -- --x64 --mac --win nsis --linux AppImage --publish never
  artifacts:
    expire_in: never
    paths:
      - dist_electron/*
  only:
    - tags
  tags:
    - gitlab-ci-learninglab-4

sign:
  stage: sign
  script:
    - echo "Triggering signing pipeline..."
    - curl -X POST -F token=$SIGN_REPO_TRIGGER_TOKEN -F ref=main $SIGN_REPO_URL
  dependencies:
    - buildAll
  only:
    - tags
  tags:
    - gitlab-ci-learninglab-4

