stages:
  - build
  - release
  - trigger_signing

# Job 1: Build-only (runs on every commit to main)
build:
  stage: build
  tags:
    - macos
  before_script:
    - chmod +x ./ci/setup_codesign.sh
    - ./ci/setup_codesign.sh
  script:
    # Install dependencies
    - npm install
    # Create env file
    - env | grep -v '^_' > .env
    # Update preview and build (without publishing)
    - npm run updatePreview
    - npm run build -- -- --publish never
  artifacts:
    paths:
      - dist/
      - dist_electron/
    expire_in: 1 week
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_COMMIT_TAG == null'

# Job 2: Build and publish (runs only on tags)
release:
  stage: release
  tags:
    - macos
  before_script:
    - chmod +x ./ci/setup_codesign.sh
    - ./ci/setup_codesign.sh
  script:
    # Install dependencies
    - npm install
    # Create env file
    - env | grep -v '^_' > .env
    # Update preview and release
    - npm run updatePreview
    - npm run release
  artifacts:
    paths:
      - dist/
      - dist_electron/
    expire_in: 1 week
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_COMMIT_TAG'

# Job 3: Trigger signing pipeline in another repository
trigger_signing:
  stage: trigger_signing
  script:
    - echo "Triggering signing pipeline..."
    - curl -X POST -F token=$SIGN_REPO_TRIGGER_TOKEN -F ref=main $SIGN_REPO_URL
  dependencies:
    - release
  tags:
    - macos
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_COMMIT_TAG'

